package dev.aftermath.testgen.generator;

import dev.aftermath.sdk.model.ErrorSnapshot;
import dev.aftermath.sdk.model.IncidentEvent;
import dev.aftermath.sdk.model.RequestSnapshot;
import dev.aftermath.testgen.model.GeneratedTestArtifact;
import dev.aftermath.testgen.model.TestFramework;
import dev.aftermath.testgen.model.TestGeneratorOptions;

import java.time.Instant;
import java.util.Map;
import java.util.UUID;

public class JUnitTestGenerator {

    public GeneratedTestArtifact generateTest(IncidentEvent incident, TestGeneratorOptions options) {
        String artifactId = UUID.randomUUID().toString();
        String timestamp = Instant.now().toString();

        if (options == null) {
            options = TestGeneratorOptions.builder()
                    .packageName("dev.aftermath.generated")
                    .className("ReproductionTest_" + incident.getIncidentId().replace("-", "_"))
                    .framework(TestFramework.JUNIT5_RESTASSURED)
                    .targetBaseUrl("http://localhost:8082")
                    .build();
        }

        String pkg = options.getPackageName() != null ? options.getPackageName() : "dev.aftermath.generated";
        String cls = options.getClassName() != null ? options.getClassName() : "ReproductionTest_" + incident.getIncidentId().replace("-", "_");
        TestFramework framework = options.getFramework() != null ? options.getFramework() : TestFramework.JUNIT5_RESTASSURED;
        String baseUrl = options.getTargetBaseUrl() != null ? options.getTargetBaseUrl() : "http://localhost:8082";

        String codeContent;
        switch (framework) {
            case JUNIT5_MOCKMVC:
                codeContent = generateMockMvcTest(pkg, cls, incident);
                break;
            case JUNIT5_WEBTESTCLIENT:
                codeContent = generateWebTestClientTest(pkg, cls, incident, baseUrl);
                break;
            case JUNIT5_WIREMOCK:
                codeContent = generateWireMockTest(pkg, cls, incident, baseUrl);
                break;
            case JUNIT5_RESTASSURED:
            default:
                codeContent = generateRestAssuredTest(pkg, cls, incident, baseUrl);
                break;
        }

        return GeneratedTestArtifact.builder()
                .artifactId(artifactId)
                .incidentId(incident.getIncidentId())
                .framework(framework.name())
                .packageName(pkg)
                .className(cls)
                .fileName(cls + ".java")
                .codeContent(codeContent)
                .createdAt(timestamp)
                .build();
    }

    private String generateRestAssuredTest(String pkg, String cls, IncidentEvent incident, String baseUrl) {
        RequestSnapshot req = incident.getRequest();
        ErrorSnapshot err = incident.getError();

        String method = req != null && req.getMethod() != null ? req.getMethod().toLowerCase() : "post";
        String uri = req != null && req.getUri() != null ? req.getUri() : "/";
        int expectedStatus = err != null && err.getStatusCode() != 0 ? err.getStatusCode() : 500;
        String body = req != null && req.getBody() != null ? req.getBody() : "";

        StringBuilder headersCode = new StringBuilder();
        if (req != null && req.getHeaders() != null) {
            for (Map.Entry<String, String> entry : req.getHeaders().entrySet()) {
                if (!entry.getKey().equalsIgnoreCase("host") && !entry.getKey().equalsIgnoreCase("content-length") 
                        && !entry.getValue().toLowerCase().contains("redacted")) {
                    headersCode.append(String.format("                .header(\"%s\", \"%s\")\n", entry.getKey(), entry.getValue()));
                }
            }
        }

        return String.format("""
package %s;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;

/**
 * Auto-generated by AFTERMATH Test Generator
 * Incident ID: %s
 * Service: %s
 */
public class %s {

    @BeforeEach
    void setUp() {
        RestAssured.baseURI = "%s";
    }

    @Test
    @DisplayName("Reproduce %s %s - %s")
    void testReproduceIncidentFailure() {
        given()
                .contentType(ContentType.JSON)
%s                .body(\"\"\"
%s
\"\"\")
        .when()
                .%s("%s")
        .then()
                .statusCode(%d);
    }
}
""", pkg, incident.getIncidentId(), 
        incident.getDeployment() != null ? incident.getDeployment().getServiceName() : "unknown",
        cls, baseUrl, 
        method.toUpperCase(), uri, err != null ? err.getExceptionClass() : "Exception",
        headersCode.toString(), body, method, uri, expectedStatus);
    }

    private String generateMockMvcTest(String pkg, String cls, IncidentEvent incident) {
        RequestSnapshot req = incident.getRequest();
        ErrorSnapshot err = incident.getError();

        String method = req != null && req.getMethod() != null ? req.getMethod().toLowerCase() : "post";
        String uri = req != null && req.getUri() != null ? req.getUri() : "/";
        int expectedStatus = err != null && err.getStatusCode() != 0 ? err.getStatusCode() : 500;
        String body = req != null && req.getBody() != null ? req.getBody() : "";

        return String.format("""
package %s;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * Auto-generated MockMvc Test by AFTERMATH Test Generator
 * Incident ID: %s
 */
@SpringBootTest
@AutoConfigureMockMvc
public class %s {

    @Autowired
    private MockMvc mockMvc;

    @Test
    @DisplayName("MockMvc Reproduction for %s %s")
    void testReproduceWithMockMvc() throws Exception {
        mockMvc.perform(%s("%s")
                .contentType(MediaType.APPLICATION_JSON)
                .content(\"\"\"
%s
\"\"\"))
                .andExpect(status().is(%d));
    }
}
""", pkg, incident.getIncidentId(), cls, method.toUpperCase(), uri, method, uri, body, expectedStatus);
    }

    private String generateWebTestClientTest(String pkg, String cls, IncidentEvent incident, String baseUrl) {
        RequestSnapshot req = incident.getRequest();
        ErrorSnapshot err = incident.getError();

        String method = req != null && req.getMethod() != null ? req.getMethod().toUpperCase() : "POST";
        String uri = req != null && req.getUri() != null ? req.getUri() : "/";
        int expectedStatus = err != null && err.getStatusCode() != 0 ? err.getStatusCode() : 500;
        String body = req != null && req.getBody() != null ? req.getBody() : "";

        return String.format("""
package %s;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.http.MediaType;
import org.springframework.test.web.reactive.server.WebTestClient;

/**
 * Auto-generated WebTestClient Test by AFTERMATH Test Generator
 * Incident ID: %s
 */
public class %s {

    private final WebTestClient webTestClient = WebTestClient.bindToServer()
            .baseUrl("%s")
            .build();

    @Test
    @DisplayName("WebTestClient Reproduction for %s %s")
    void testReproduceWithWebTestClient() {
        webTestClient.%s()
                .uri("%s")
                .contentType(MediaType.APPLICATION_JSON)
                .bodyValue(\"\"\"
%s
\"\"\")
                .exchange()
                .expectStatus().isEqualTo(%d);
    }
}
""", pkg, incident.getIncidentId(), cls, baseUrl, method, uri, method.toLowerCase(), uri, body, expectedStatus);
    }

    private String generateWireMockTest(String pkg, String cls, IncidentEvent incident, String baseUrl) {
        RequestSnapshot req = incident.getRequest();
        ErrorSnapshot err = incident.getError();

        String method = req != null && req.getMethod() != null ? req.getMethod().toUpperCase() : "POST";
        String uri = req != null && req.getUri() != null ? req.getUri() : "/";
        int expectedStatus = err != null && err.getStatusCode() != 0 ? err.getStatusCode() : 500;
        String body = req != null && req.getBody() != null ? req.getBody() : "";

        return String.format("""
package %s;

import com.github.tomakehurst.wiremock.WireMockServer;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.github.tomakehurst.wiremock.client.WireMock.*;
import static com.github.tomakehurst.wiremock.core.WireMockConfiguration.wireMockConfig;
import static io.restassured.RestAssured.given;

/**
 * Auto-generated Standalone WireMock Integration Test by AFTERMATH Test Generator
 * Incident ID: %s
 * Includes WireMock server stubbing for zero-dependency CI/CD execution.
 */
public class %s {

    private static WireMockServer wireMockServer;

    @BeforeAll
    static void startWireMock() {
        wireMockServer = new WireMockServer(wireMockConfig().dynamicPort());
        wireMockServer.start();
        configureFor("localhost", wireMockServer.port());
        RestAssured.baseURI = "http://localhost:" + wireMockServer.port();

        // Stub target endpoint to match captured production error response
        stubFor(%s(urlEqualTo("%s"))
                .willReturn(aResponse()
                        .withStatus(%d)
                        .withHeader("Content-Type", "application/json")
                        .withBody("{\"error\": \"%s\"}")));
    }

    @AfterAll
    static void stopWireMock() {
        if (wireMockServer != null) {
            wireMockServer.stop();
        }
    }

    @Test
    @DisplayName("WireMock Standalone Reproduction - %s %s")
    void testReproduceWithWireMockStub() {
        given()
                .contentType(ContentType.JSON)
                .body(\"\"\"
%s
\"\"\")
        .when()
                .%s("%s")
        .then()
                .statusCode(%d);
    }
}
""", pkg, incident.getIncidentId(), cls, method.toLowerCase(), uri, expectedStatus,
        err != null ? err.getExceptionClass() : "Exception",
        method, uri, body, method.toLowerCase(), uri, expectedStatus);
    }
}
