server:
  port: 8090

spring:
  application:
    name: aftermath-collector
  datasource:
    url: jdbc:h2:file:./aftermath_collector_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

aftermath:
  sdk:
    enabled: false
