package dev.aftermath.collector.service;

import dev.aftermath.collector.entity.IncidentEntity;
import dev.aftermath.collector.repository.IncidentRepository;
import dev.aftermath.sdk.model.ErrorSnapshot;
import dev.aftermath.sdk.model.IncidentEvent;
import dev.aftermath.sdk.model.RequestSnapshot;
import dev.aftermath.testgen.generator.JUnitTestGenerator;
import dev.aftermath.testgen.model.GeneratedTestArtifact;
import dev.aftermath.testgen.model.TestFramework;
import dev.aftermath.testgen.model.TestGeneratorOptions;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class GitPrBotService {

    private final IncidentRepository incidentRepository;
    private final AnalysisService analysisService;
    private final JUnitTestGenerator testGenerator = new JUnitTestGenerator();

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class GitPrPayload {
        private String incidentId;
        private String branchName;
        private String prTitle;
        private String prMarkdownBody;
        private String testFileName;
        private String testCodeContent;
        private String targetClassToFix;
        private String suggestedGitDiff;
    }

    public GitPrPayload generatePrPayload(String incidentId) {
        IncidentEntity entity = incidentRepository.findByIncidentId(incidentId)
                .orElseThrow(() -> new IllegalArgumentException("Incident not found: " + incidentId));

        AnalysisService.AnalysisResult analysis = analysisService.analyzeIncident(incidentId);

        // Reconstruct IncidentEvent for Test Generator
        RequestSnapshot reqSnapshot = new RequestSnapshot();
        reqSnapshot.setMethod(entity.getHttpMethod());
        reqSnapshot.setUri(entity.getRequestUri());

        ErrorSnapshot errSnapshot = new ErrorSnapshot();
        errSnapshot.setStatusCode(entity.getStatusCode() != null ? entity.getStatusCode() : 500);
        errSnapshot.setExceptionClass(entity.getExceptionClass());
        errSnapshot.setMessage(entity.getExceptionMessage());
        errSnapshot.setStackTrace(entity.getStackTrace());

        IncidentEvent incidentEvent = new IncidentEvent();
        incidentEvent.setIncidentId(entity.getIncidentId());
        incidentEvent.setRequest(reqSnapshot);
        incidentEvent.setError(errSnapshot);

        TestGeneratorOptions options = TestGeneratorOptions.builder()
                .packageName("dev.aftermath.generated")
                .className("ReproductionTest_" + incidentId.replace("-", "_"))
                .framework(TestFramework.JUNIT5_WIREMOCK)
                .targetBaseUrl("http://localhost:8082")
                .build();

        GeneratedTestArtifact artifact = testGenerator.generateTest(incidentEvent, options);

        String branchName = "aftermath/fix-incident-" + incidentId.substring(0, 8);
        String prTitle = String.format("fix(%s): resolve %s in %s",
                entity.getServiceName() != null ? entity.getServiceName() : "service",
                entity.getExceptionClass() != null ? entity.getExceptionClass() : "Exception",
                analysis.getFailingClass());

        String prBody = String.format("""
## 🤖 AFTERMATH Automated Bug Reproduction & Fix Pull Request

### Incident Details
- **Incident ID**: `%s`
- **Exception**: `%s`
- **Failing Location**: `%s.%s` (Line %d)
- **Service**: `%s`

### 💡 Root Cause Summary
%s

### 🔧 Recommended Fix
%s

### 🧪 Included Automated Reproduction Test
A standalone JUnit 5 + WireMock reproduction test has been generated and added under:
`src/test/java/%s/%s`

---
*Auto-generated by AFTERMATH Enterprise Automation Engine*
""", incidentId, entity.getExceptionClass(), analysis.getFailingClass(), analysis.getFailingMethod(),
                analysis.getLineNumber(), entity.getServiceName(), analysis.getRootCauseSummary(),
                analysis.getRecommendedFix(), artifact.getPackageName().replace(".", "/"), artifact.getFileName());

        return GitPrPayload.builder()
                .incidentId(incidentId)
                .branchName(branchName)
                .prTitle(prTitle)
                .prMarkdownBody(prBody)
                .testFileName(artifact.getFileName())
                .testCodeContent(artifact.getCodeContent())
                .targetClassToFix(analysis.getFailingClass())
                .suggestedGitDiff(analysis.getSuggestedDiff())
                .build();
    }
}
